name: teacher_attendenc
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  curved_navigation_bar: ^1.0.6
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.6
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  google_maps_flutter: ^2.7.0
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  table_calendar: ^3.1.2
  http: ^1.2.1
  
dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
